/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.13/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    id("maven-publish")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    google()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation("net.java.dev.jna:jna:5.17.0")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

afterEvaluate {
    publishing {
        publications {
            register<MavenPublication>("mavenJava") {
                groupId = "upinn.tech"
                artifactId = "safepasswordlib"
                version = "1.0.4"

                // Cambiar de 'release' a 'java' para librerías JVM
                from(components["java"])

                pom {
                    name.set("Safe Password Rust Lib")
                    description.set("Librería Kotlin que utiliza Rust `safe_password` y JNA para generar contraseñas seguras.")
                    url.set("https://github.com/wuilmerj24/SafePasswordRustLib.git")
                    licenses {
                        license {
                            name.set("Apache-2.0 license")
                            url.set("https://github.com/wuilmerj24/SafePasswordRustLib/blob/main/LICENSE")
                            distribution.set("repo")
                        }
                    }
                    developers {
                        developer {
                            id.set("wuilmerj24")
                            name.set("Upinn")
                        }
                    }
                    scm {
                        connection.set("scm:git:github.com/wuilmerj24/SafePasswordRustLib.git")
                        developerConnection.set("scm:git:ssh://github.com/wuilmerj24/SafePasswordRustLib.git")
                        url.set("https://github.com/wuilmerj24/SafePasswordRustLib/tree/main")
                    }
                }
            }
        }

        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/wuilmerj24/SafePasswordRustLib")
                credentials {
                    username = System.getenv("GITHUB_USERNAME")
                    password = System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
